' ImportCurves.vbs - generated by `fus push`. Do not edit; rewritten every push.
' Part: trainer40    curves to refresh: 3
'
' Refreshes curve features in place, and inserts any that do not exist yet.
' A newly inserted curve still has to be added to the surface by hand.

Option Explicit

Dim PART_NAME, OUT_DIR, names, files, progIds
PART_NAME = "trainer40"
OUT_DIR   = "C:\Users\M0obo\Desktop\Planes\exports\trainer40\"
names = Array("S1", "S2", "keel")
files = Array("trainer40_S1.sldcrv", "trainer40_S2.sldcrv", "trainer40_G_keel.sldcrv")
progIds = Array("SldWorks.Application.34", "SldWorks.Application.32", "SldWorks.Application")

Dim swApp, swModel, i, okCount, failCount
okCount = 0
failCount = 0

Set swApp = Attach(progIds)
If swApp Is Nothing Then
    WScript.Echo "FATAL   no running SolidWorks reachable over COM."
    WScript.Echo "        Tried: " & Join(progIds, ", ")
    WScript.Echo "        Check that " & PART_NAME & ".sldprt is open, and that SolidWorks"
    WScript.Echo "        is not running elevated while this script is not."
    WScript.Echo "        To start an instance instead: fus push --allow-create"
    WScript.Quit 2
End If

Set swModel = FindDoc(swApp, PART_NAME)
If swModel Is Nothing Then
    WScript.Echo "FATAL   " & PART_NAME & ".sldprt is not open in SolidWorks."
    WScript.Quit 2
End If
WScript.Echo "part    " & swModel.GetTitle()

If UBound(names) < 0 Then
    WScript.Echo "done    nothing to refresh; every curve already matches the export."
    WScript.Quit 0
End If

For i = 0 To UBound(names)
    If RefreshCurve(swModel, names(i), OUT_DIR & files(i)) Then
        okCount = okCount + 1
    Else
        failCount = failCount + 1
    End If
Next

' One rebuild at the end. Mid-refresh the guides genuinely do not pierce the
' sections, so the surface is expected to be in error until the last curve
' lands - see DECISIONS.md.
Dim rebuilt
On Error Resume Next
rebuilt = swModel.ForceRebuild3(False)
If Err.Number <> 0 Then
    WScript.Echo "warn    rebuild raised: " & Err.Description
    Err.Clear
Else
    WScript.Echo "rebuild " & CStr(rebuilt)
End If
On Error GoTo 0

WScript.Echo "done    " & okCount & " refreshed, " & failCount & " failed"
If failCount > 0 Then WScript.Quit 1
WScript.Quit 0

' ---------------------------------------------------------------- helpers

' Try each ProgID against the Running Object Table and take the first hit.
Function Attach(ids)
    Dim k, app
    Set Attach = Nothing
    On Error Resume Next
    For k = 0 To UBound(ids)
        Err.Clear
        Set app = GetObject(, ids(k))
        If Err.Number = 0 And Not app Is Nothing Then
            WScript.Echo "attach  " & ids(k)
            Set Attach = app
            Err.Clear
            On Error GoTo 0
            Exit Function
        End If
    Next
    Err.Clear
    On Error GoTo 0
End Function

Function FindDoc(app, partName)
    Dim d, nxt, guard
    Set FindDoc = Nothing
    On Error Resume Next
    Set d = app.ActiveDoc
    If Err.Number = 0 And Not d Is Nothing Then
        If InStr(1, d.GetTitle(), partName, 1) > 0 Then
            Set FindDoc = d
            On Error GoTo 0
            Exit Function
        End If
    End If
    Err.Clear
    ' Fall back to walking the open documents. The guard matters: if GetNext
    ' errors, d would keep its old value and the loop would never end.
    Set d = app.GetFirstDocument()
    guard = 0
    Do While (Not d Is Nothing) And guard < 200
        guard = guard + 1
        If InStr(1, d.GetTitle(), partName, 1) > 0 Then
            Set FindDoc = d
            On Error GoTo 0
            Exit Function
        End If
        Set nxt = Nothing
        Set nxt = d.GetNext()
        If Err.Number <> 0 Or nxt Is Nothing Then
            Err.Clear
            Exit Do
        End If
        Set d = nxt
    Loop
    On Error GoTo 0
End Function

Function FindFeature(model, featName)
    Dim f, guard
    Set FindFeature = Nothing
    Set f = model.FirstFeature()
    guard = 0
    Do While (Not f Is Nothing) And guard < 5000
        guard = guard + 1
        If f.Name = featName Then
            Set FindFeature = f
            Exit Function
        End If
        Set f = f.GetNextFeature()
    Loop
End Function

' Insert a missing curve from its file and give it the name push expects.
Function InsertCurve(model, featName, path)
    Dim before, feat, ok
    InsertCurve = False
    before = LastFeatureName(model)
    On Error Resume Next
    ok = model.InsertCurveFile(path)
    If Err.Number <> 0 Then
        WScript.Echo "  FAIL    " & featName & " - InsertCurveFile: " & Err.Description
        Err.Clear
        Exit Function
    End If
    On Error GoTo 0
    If Not ok Then
        WScript.Echo "  FAIL    " & featName & " - InsertCurveFile returned False"
        Exit Function
    End If
    Set feat = LastFeature(model)
    If feat Is Nothing Then
        WScript.Echo "  FAIL    " & featName & " - inserted, but the new feature was not found"
        Exit Function
    End If
    If feat.Name = before Then
        WScript.Echo "  FAIL    " & featName & " - InsertCurveFile added no feature"
        Exit Function
    End If
    On Error Resume Next
    feat.Name = featName
    If Err.Number <> 0 Then
        WScript.Echo "  WARN    inserted as " & feat.Name & ", could not rename to " & featName
        Err.Clear
        Exit Function
    End If
    On Error GoTo 0
    WScript.Echo "  NEW     " & featName & " - inserted; still needs adding to the surface by hand"
    InsertCurve = True
End Function

Function LastFeature(model)
    Dim f, last, guard
    Set last = Nothing
    Set f = model.FirstFeature()
    guard = 0
    Do While (Not f Is Nothing) And guard < 5000
        guard = guard + 1
        Set last = f
        Set f = f.GetNextFeature()
    Loop
    Set LastFeature = last
End Function

Function LastFeatureName(model)
    Dim f
    LastFeatureName = ""
    Set f = LastFeature(model)
    If Not f Is Nothing Then LastFeatureName = f.Name
End Function

Function RefreshCurve(model, featName, path)
    Dim feat, data, typeName, modified
    RefreshCurve = False

    Set feat = FindFeature(model, featName)
    If feat Is Nothing Then
        RefreshCurve = InsertCurve(model, featName, path)
        Exit Function
    End If

    typeName = "?"
    On Error Resume Next
    typeName = feat.GetTypeName2()
    Err.Clear

    Set data = feat.GetDefinition()
    If Err.Number <> 0 Or data Is Nothing Then
        WScript.Echo "  FAIL    " & featName & " - no feature definition (type " & typeName & "): " & Err.Description
        Err.Clear
        Exit Function
    End If

    data.LoadPointsFromFile path
    If Err.Number <> 0 Then
        WScript.Echo "  FAIL    " & featName & " - LoadPointsFromFile not supported on type " & typeName & ": " & Err.Description
        Err.Clear
        Exit Function
    End If

    modified = feat.ModifyDefinition(data, model, Nothing)
    If Err.Number <> 0 Then
        WScript.Echo "  FAIL    " & featName & " - ModifyDefinition: " & Err.Description
        Err.Clear
        Exit Function
    End If
    On Error GoTo 0

    If modified Then
        WScript.Echo "  ok      " & featName
        RefreshCurve = True
    Else
        WScript.Echo "  FAIL    " & featName & " - ModifyDefinition returned False (type " & typeName & ")"
    End If
End Function
