' S4_section.bas - generated by fus (Fuselage-Builder). Do not hand-edit; regenerate from fuselage.json.
'
' UNITS: every coordinate, radius and linear dimension below is in METRES, the
' SolidWorks API's own unit. This sketch's source data is millimetres; each value
' has already been divided by 1000 on the way out. Angle values (radians) are
' unconverted. See src/sketch/sw.ts if this macro's shape looks 1000x too big or
' too small - that is the one bug this file exists to prevent.
'
' PLANE: not stated by the caller — pick the station plane and select it (or the face) before running this macro.
' This macro never creates or selects a plane. SKETCH-PLAN §3: wiring geometry
' into the model is always a human job here, the same way `fus push --insert`
' creates a curve but never adds it to the Boundary Surface.
'
' ENTITIES: 35   RELATIONS: 12   DIMENSIONS: 12
' MANUAL STEPS: this sketch cannot be fully automated over COM. Marked
' "SW-MANUAL:" below, and counted here rather than left to be discovered:
'   - 8 relation(s) targeting a spline tangent handle
'   - 8 dimension(s) targeting a spline tangent handle
'   - 1 relation(s) naming a spline's own interior fit point
'
' This file's mapping from this app's relation/dimension vocabulary to SolidWorks'
' own names is RELATION_CONSTRAINT / DIMENSION_TYPE in src/sketch/sw.ts, not
' repeated per-line here. Verified as well-formed VBA against the documented API
' surface; not executed against SolidWorks, which nothing in this repo has.
'
Option Explicit

Sub CreateSketch()
    Dim swApp As Object, Part As Object
    Set swApp = Application.SldWorks
    Set Part = swApp.ActiveDoc
    If Part Is Nothing Then
        MsgBox "Open the target part and select the sketch plane first."
        Exit Sub
    End If

    ' Uses whatever plane or face is currently selected. See the header comment.
    Part.SketchManager.InsertSketch True

    ' ------------------------------------------------------------ entities
    ' P_origin
    Dim v_P_origin As Object
    Set v_P_origin = Part.SketchManager.CreatePoint(0.000000000, 0.000000000, 0)
    v_P_origin.ConstructionGeometry = True
    ' NOTE: whether a bare sketch point exposes ConstructionGeometry varies by
    ' SolidWorks version - verify the toggle actually took if this line errors.

    ' P_crown
    Dim v_P_crown As Object
    Set v_P_crown = Part.SketchManager.CreatePoint(0.000000000, 0.045000000, 0)

    ' P_keel
    Dim v_P_keel As Object
    Set v_P_keel = Part.SketchManager.CreatePoint(0.000000000, -0.040000000, 0)

    ' P_stbd
    Dim v_P_stbd As Object
    Set v_P_stbd = Part.SketchManager.CreatePoint(0.060000000, 0.000000000, 0)

    ' P_port
    Dim v_P_port As Object
    Set v_P_port = Part.SketchManager.CreatePoint(-0.060000000, 0.000000000, 0)

    ' L_centreline: line P_keel -> P_crown
    Dim v_L_centreline As Object
    Set v_L_centreline = Part.SketchManager.CreateLine2(0.000000000, -0.040000000, 0, 0.000000000, 0.045000000, 0)
    v_L_centreline.ConstructionGeometry = True
    Part.ClearSelection2 True
    v_P_keel.Select4 False, Nothing
    v_L_centreline.GetStartPoint2().Select4 True, Nothing
    Part.SketchManager.AddConstraint "sgCOINCIDENT"  ' weld: L_centreline start == P_keel
    Part.ClearSelection2 True
    v_P_crown.Select4 False, Nothing
    v_L_centreline.GetEndPoint2().Select4 True, Nothing
    Part.SketchManager.AddConstraint "sgCOINCIDENT"  ' weld: L_centreline end == P_crown

    ' L_waterline: line P_port -> P_stbd
    Dim v_L_waterline As Object
    Set v_L_waterline = Part.SketchManager.CreateLine2(-0.060000000, 0.000000000, 0, 0.060000000, 0.000000000, 0)
    v_L_waterline.ConstructionGeometry = True
    Part.ClearSelection2 True
    v_P_port.Select4 False, Nothing
    v_L_waterline.GetStartPoint2().Select4 True, Nothing
    Part.SketchManager.AddConstraint "sgCOINCIDENT"  ' weld: L_waterline start == P_port
    Part.ClearSelection2 True
    v_P_stbd.Select4 False, Nothing
    v_L_waterline.GetEndPoint2().Select4 True, Nothing
    Part.SketchManager.AddConstraint "sgCOINCIDENT"  ' weld: L_waterline end == P_stbd

    ' SP_stbd_upper: spline through P_stbd, P_SU_1, P_SU_2, P_SU_3, P_SU_4, P_SU_5, P_SU_6, P_SU_7, P_crown
    Dim pts_SP_stbd_upper(26) As Double
    pts_SP_stbd_upper(0) = 0.060000000 : pts_SP_stbd_upper(1) = 0.000000000 : pts_SP_stbd_upper(2) = 0
    pts_SP_stbd_upper(3) = 0.059390179 : pts_SP_stbd_upper(4) = 0.010758158 : pts_SP_stbd_upper(5) = 0
    pts_SP_stbd_upper(6) = 0.056370090 : pts_SP_stbd_upper(7) = 0.021072690 : pts_SP_stbd_upper(8) = 0
    pts_SP_stbd_upper(9) = 0.050275470 : pts_SP_stbd_upper(10) = 0.029912396 : pts_SP_stbd_upper(11) = 0
    pts_SP_stbd_upper(12) = 0.041781920 : pts_SP_stbd_upper(13) = 0.036504446 : pts_SP_stbd_upper(14) = 0
    pts_SP_stbd_upper(15) = 0.031949155 : pts_SP_stbd_upper(16) = 0.040891458 : pts_SP_stbd_upper(17) = 0
    pts_SP_stbd_upper(18) = 0.021490572 : pts_SP_stbd_upper(19) = 0.043487025 : pts_SP_stbd_upper(20) = 0
    pts_SP_stbd_upper(21) = 0.010780360 : pts_SP_stbd_upper(22) = 0.044717394 : pts_SP_stbd_upper(23) = 0
    pts_SP_stbd_upper(24) = 0.000000000 : pts_SP_stbd_upper(25) = 0.045000000 : pts_SP_stbd_upper(26) = 0
    Dim v_SP_stbd_upper As Object
    Set v_SP_stbd_upper = Part.SketchManager.CreateSpline(pts_SP_stbd_upper)
    Part.ClearSelection2 True
    v_P_stbd.Select4 False, Nothing
    v_SP_stbd_upper.GetStartPoint2().Select4 True, Nothing
    Part.SketchManager.AddConstraint "sgCOINCIDENT"  ' weld: SP_stbd_upper start == P_stbd
    Part.ClearSelection2 True
    v_P_crown.Select4 False, Nothing
    v_SP_stbd_upper.GetEndPoint2().Select4 True, Nothing
    Part.SketchManager.AddConstraint "sgCOINCIDENT"  ' weld: SP_stbd_upper end == P_crown
    ' 7 interior fit point(s) of SP_stbd_upper - P_SU_1, P_SU_2, P_SU_3, P_SU_4, P_SU_5, P_SU_6, P_SU_7 - get no
    ' standalone point object: CreateSpline above already placed a through-point at
    ' each one's exact coordinate, and nothing else in this sketch needs an
    ' independently selectable point there (standalonePointIds, src/sketch/sw.ts). A
    ' relation or dimension naming one of these ids by itself is flagged as a manual
    ' step in the relations/dimensions sections below rather than repeated here.

    ' SP_stbd_lower: spline through P_stbd, P_SL_1, P_SL_2, P_SL_3, P_SL_4, P_SL_5, P_keel
    Dim pts_SP_stbd_lower(20) As Double
    pts_SP_stbd_lower(0) = 0.060000000 : pts_SP_stbd_lower(1) = 0.000000000 : pts_SP_stbd_lower(2) = 0
    pts_SP_stbd_lower(3) = 0.058291388 : pts_SP_stbd_lower(4) = -0.011706315 : pts_SP_stbd_lower(5) = 0
    pts_SP_stbd_lower(6) = 0.053222276 : pts_SP_stbd_lower(7) = -0.021300822 : pts_SP_stbd_lower(8) = 0
    pts_SP_stbd_lower(9) = 0.044949212 : pts_SP_stbd_lower(10) = -0.029189602 : pts_SP_stbd_lower(11) = 0
    pts_SP_stbd_lower(12) = 0.033673861 : pts_SP_stbd_lower(13) = -0.035096973 : pts_SP_stbd_lower(14) = 0
    pts_SP_stbd_lower(15) = 0.019452770 : pts_SP_stbd_lower(16) = -0.038758996 : pts_SP_stbd_lower(17) = 0
    pts_SP_stbd_lower(18) = 0.000000000 : pts_SP_stbd_lower(19) = -0.040000000 : pts_SP_stbd_lower(20) = 0
    Dim v_SP_stbd_lower As Object
    Set v_SP_stbd_lower = Part.SketchManager.CreateSpline(pts_SP_stbd_lower)
    Part.ClearSelection2 True
    v_P_stbd.Select4 False, Nothing
    v_SP_stbd_lower.GetStartPoint2().Select4 True, Nothing
    Part.SketchManager.AddConstraint "sgCOINCIDENT"  ' weld: SP_stbd_lower start == P_stbd
    Part.ClearSelection2 True
    v_P_keel.Select4 False, Nothing
    v_SP_stbd_lower.GetEndPoint2().Select4 True, Nothing
    Part.SketchManager.AddConstraint "sgCOINCIDENT"  ' weld: SP_stbd_lower end == P_keel
    ' 5 interior fit point(s) of SP_stbd_lower - P_SL_1, P_SL_2, P_SL_3, P_SL_4, P_SL_5 - get no
    ' standalone point object: CreateSpline above already placed a through-point at
    ' each one's exact coordinate, and nothing else in this sketch needs an
    ' independently selectable point there (standalonePointIds, src/sketch/sw.ts). A
    ' relation or dimension naming one of these ids by itself is flagged as a manual
    ' step in the relations/dimensions sections below rather than repeated here.

    ' SP_port_upper: spline through P_port, P_PU_1, P_PU_2, P_PU_3, P_PU_4, P_PU_5, P_PU_6, P_PU_7, P_crown
    Dim pts_SP_port_upper(26) As Double
    pts_SP_port_upper(0) = -0.060000000 : pts_SP_port_upper(1) = 0.000000000 : pts_SP_port_upper(2) = 0
    pts_SP_port_upper(3) = -0.059390179 : pts_SP_port_upper(4) = 0.010758158 : pts_SP_port_upper(5) = 0
    pts_SP_port_upper(6) = -0.056370090 : pts_SP_port_upper(7) = 0.021072690 : pts_SP_port_upper(8) = 0
    pts_SP_port_upper(9) = -0.050275470 : pts_SP_port_upper(10) = 0.029912396 : pts_SP_port_upper(11) = 0
    pts_SP_port_upper(12) = -0.041781920 : pts_SP_port_upper(13) = 0.036504446 : pts_SP_port_upper(14) = 0
    pts_SP_port_upper(15) = -0.031949155 : pts_SP_port_upper(16) = 0.040891458 : pts_SP_port_upper(17) = 0
    pts_SP_port_upper(18) = -0.021490572 : pts_SP_port_upper(19) = 0.043487025 : pts_SP_port_upper(20) = 0
    pts_SP_port_upper(21) = -0.010780360 : pts_SP_port_upper(22) = 0.044717394 : pts_SP_port_upper(23) = 0
    pts_SP_port_upper(24) = 0.000000000 : pts_SP_port_upper(25) = 0.045000000 : pts_SP_port_upper(26) = 0
    Dim v_SP_port_upper As Object
    Set v_SP_port_upper = Part.SketchManager.CreateSpline(pts_SP_port_upper)
    Part.ClearSelection2 True
    v_P_port.Select4 False, Nothing
    v_SP_port_upper.GetStartPoint2().Select4 True, Nothing
    Part.SketchManager.AddConstraint "sgCOINCIDENT"  ' weld: SP_port_upper start == P_port
    Part.ClearSelection2 True
    v_P_crown.Select4 False, Nothing
    v_SP_port_upper.GetEndPoint2().Select4 True, Nothing
    Part.SketchManager.AddConstraint "sgCOINCIDENT"  ' weld: SP_port_upper end == P_crown
    ' 7 interior fit point(s) of SP_port_upper - P_PU_1, P_PU_2, P_PU_3, P_PU_4, P_PU_5, P_PU_6, P_PU_7 - get no
    ' standalone point object: CreateSpline above already placed a through-point at
    ' each one's exact coordinate, and nothing else in this sketch needs an
    ' independently selectable point there (standalonePointIds, src/sketch/sw.ts). A
    ' relation or dimension naming one of these ids by itself is flagged as a manual
    ' step in the relations/dimensions sections below rather than repeated here.

    ' SP_port_lower: spline through P_port, P_PL_1, P_PL_2, P_PL_3, P_PL_4, P_PL_5, P_keel
    Dim pts_SP_port_lower(20) As Double
    pts_SP_port_lower(0) = -0.060000000 : pts_SP_port_lower(1) = 0.000000000 : pts_SP_port_lower(2) = 0
    pts_SP_port_lower(3) = -0.058291388 : pts_SP_port_lower(4) = -0.011706315 : pts_SP_port_lower(5) = 0
    pts_SP_port_lower(6) = -0.053222276 : pts_SP_port_lower(7) = -0.021300822 : pts_SP_port_lower(8) = 0
    pts_SP_port_lower(9) = -0.044949212 : pts_SP_port_lower(10) = -0.029189602 : pts_SP_port_lower(11) = 0
    pts_SP_port_lower(12) = -0.033673861 : pts_SP_port_lower(13) = -0.035096973 : pts_SP_port_lower(14) = 0
    pts_SP_port_lower(15) = -0.019452770 : pts_SP_port_lower(16) = -0.038758996 : pts_SP_port_lower(17) = 0
    pts_SP_port_lower(18) = 0.000000000 : pts_SP_port_lower(19) = -0.040000000 : pts_SP_port_lower(20) = 0
    Dim v_SP_port_lower As Object
    Set v_SP_port_lower = Part.SketchManager.CreateSpline(pts_SP_port_lower)
    Part.ClearSelection2 True
    v_P_port.Select4 False, Nothing
    v_SP_port_lower.GetStartPoint2().Select4 True, Nothing
    Part.SketchManager.AddConstraint "sgCOINCIDENT"  ' weld: SP_port_lower start == P_port
    Part.ClearSelection2 True
    v_P_keel.Select4 False, Nothing
    v_SP_port_lower.GetEndPoint2().Select4 True, Nothing
    Part.SketchManager.AddConstraint "sgCOINCIDENT"  ' weld: SP_port_lower end == P_keel
    ' 5 interior fit point(s) of SP_port_lower - P_PL_1, P_PL_2, P_PL_3, P_PL_4, P_PL_5 - get no
    ' standalone point object: CreateSpline above already placed a through-point at
    ' each one's exact coordinate, and nothing else in this sketch needs an
    ' independently selectable point there (standalonePointIds, src/sketch/sw.ts). A
    ' relation or dimension naming one of these ids by itself is flagged as a manual
    ' step in the relations/dimensions sections below rather than repeated here.

    ' ----------------------------------------------------------- relations
    ' R_centreline_vertical: vertical on L_centreline
    Part.ClearSelection2 True
    v_L_centreline.Select4 False, Nothing
    Part.SketchManager.AddConstraint "sgVERTICAL2D"

    ' R_centreline_origin: pointOnEntity on P_origin, L_centreline
    Part.ClearSelection2 True
    v_P_origin.Select4 False, Nothing
    v_L_centreline.Select4 True, Nothing
    Part.SketchManager.AddConstraint "sgCOINCIDENT"

    ' R_symmetric_port: symmetric on P_stbd, P_port, L_centreline
    Part.ClearSelection2 True
    v_P_stbd.Select4 False, Nothing
    v_P_port.Select4 True, Nothing
    v_L_centreline.Select4 True, Nothing
    Part.SketchManager.AddConstraint "sgSYMMETRIC"

    ' SW-MANUAL: R_SU_start (vertical) cannot be a live COM call - see the file header.
    ' By hand:
    '   1. select the forward-reaching arrow of the handle on point 1 of SP_stbd_upper
    '   2. Tools > Relations > sgVERTICAL2D (vertical)

    ' SW-MANUAL: R_SU_end (horizontal) cannot be a live COM call - see the file header.
    ' By hand:
    '   1. select the back-reaching arrow of the handle on point 9 of SP_stbd_upper
    '   2. Tools > Relations > sgHORIZONTAL2D (horizontal)

    ' SW-MANUAL: R_SL_start (vertical) cannot be a live COM call - see the file header.
    ' By hand:
    '   1. select the forward-reaching arrow of the handle on point 1 of SP_stbd_lower
    '   2. Tools > Relations > sgVERTICAL2D (vertical)

    ' SW-MANUAL: R_SL_end (horizontal) cannot be a live COM call - see the file header.
    ' By hand:
    '   1. select the back-reaching arrow of the handle on point 7 of SP_stbd_lower
    '   2. Tools > Relations > sgHORIZONTAL2D (horizontal)

    ' SW-MANUAL: R_PU_start (vertical) cannot be a live COM call - see the file header.
    ' By hand:
    '   1. select the forward-reaching arrow of the handle on point 1 of SP_port_upper
    '   2. Tools > Relations > sgVERTICAL2D (vertical)

    ' SW-MANUAL: R_PU_end (horizontal) cannot be a live COM call - see the file header.
    ' By hand:
    '   1. select the back-reaching arrow of the handle on point 9 of SP_port_upper
    '   2. Tools > Relations > sgHORIZONTAL2D (horizontal)

    ' SW-MANUAL: R_PL_start (vertical) cannot be a live COM call - see the file header.
    ' By hand:
    '   1. select the forward-reaching arrow of the handle on point 1 of SP_port_lower
    '   2. Tools > Relations > sgVERTICAL2D (vertical)

    ' SW-MANUAL: R_PL_end (horizontal) cannot be a live COM call - see the file header.
    ' By hand:
    '   1. select the back-reaching arrow of the handle on point 7 of SP_port_lower
    '   2. Tools > Relations > sgHORIZONTAL2D (horizontal)

    ' SW-MANUAL: R_fix_interior (fix) cannot be a live COM call - see the file header.
    ' By hand:
    '   1. select P_SU_1 (an interior fit point on its spline - select it in the graphics area)
    '   2. select P_SU_2 (an interior fit point on its spline - select it in the graphics area)
    '   3. select P_SU_3 (an interior fit point on its spline - select it in the graphics area)
    '   4. select P_SU_4 (an interior fit point on its spline - select it in the graphics area)
    '   5. select P_SU_5 (an interior fit point on its spline - select it in the graphics area)
    '   6. select P_SU_6 (an interior fit point on its spline - select it in the graphics area)
    '   7. select P_SU_7 (an interior fit point on its spline - select it in the graphics area)
    '   8. select P_SL_1 (an interior fit point on its spline - select it in the graphics area)
    '   9. select P_SL_2 (an interior fit point on its spline - select it in the graphics area)
    '   10. select P_SL_3 (an interior fit point on its spline - select it in the graphics area)
    '   11. select P_SL_4 (an interior fit point on its spline - select it in the graphics area)
    '   12. select P_SL_5 (an interior fit point on its spline - select it in the graphics area)
    '   13. select P_PU_1 (an interior fit point on its spline - select it in the graphics area)
    '   14. select P_PU_2 (an interior fit point on its spline - select it in the graphics area)
    '   15. select P_PU_3 (an interior fit point on its spline - select it in the graphics area)
    '   16. select P_PU_4 (an interior fit point on its spline - select it in the graphics area)
    '   17. select P_PU_5 (an interior fit point on its spline - select it in the graphics area)
    '   18. select P_PU_6 (an interior fit point on its spline - select it in the graphics area)
    '   19. select P_PU_7 (an interior fit point on its spline - select it in the graphics area)
    '   20. select P_PL_1 (an interior fit point on its spline - select it in the graphics area)
    '   21. select P_PL_2 (an interior fit point on its spline - select it in the graphics area)
    '   22. select P_PL_3 (an interior fit point on its spline - select it in the graphics area)
    '   23. select P_PL_4 (an interior fit point on its spline - select it in the graphics area)
    '   24. select P_PL_5 (an interior fit point on its spline - select it in the graphics area)
    '   25. Tools > Relations > sgFIXED (fix)


    ' ---------------------------------------------------------- dimensions
    ' D_halfWidth (D1): horizontal on P_origin, P_stbd
    Part.ClearSelection2 True
    v_P_origin.Select4 False, Nothing
    v_P_stbd.Select4 True, Nothing
    Dim disp_D_halfWidth As Object
    Set disp_D_halfWidth = Part.Extension.AddDimension2(0.030000000, 0.012000000, 0)
    If Not disp_D_halfWidth Is Nothing Then
        disp_D_halfWidth.Dimension.Name = "D1"
        disp_D_halfWidth.Dimension.SystemValue = 0.060000000  ' 60 mm
    Else
        Debug.Print "FAIL  D_halfWidth (D1) - AddDimension2 returned Nothing; the selection above may not support a swDistanceDim"
    End If

    ' D_crown (D2): vertical on P_origin, P_crown
    Part.ClearSelection2 True
    v_P_origin.Select4 False, Nothing
    v_P_crown.Select4 True, Nothing
    Dim disp_D_crown As Object
    Set disp_D_crown = Part.Extension.AddDimension2(-0.009000000, 0.022500000, 0)
    If Not disp_D_crown Is Nothing Then
        disp_D_crown.Dimension.Name = "D2"
        disp_D_crown.Dimension.SystemValue = 0.045000000  ' 45 mm
    Else
        Debug.Print "FAIL  D_crown (D2) - AddDimension2 returned Nothing; the selection above may not support a swDistanceDim"
    End If

    ' D_keel (D3): vertical on P_origin, P_keel
    Part.ClearSelection2 True
    v_P_origin.Select4 False, Nothing
    v_P_keel.Select4 True, Nothing
    Dim disp_D_keel As Object
    Set disp_D_keel = Part.Extension.AddDimension2(-0.008000000, -0.020000000, 0)
    If Not disp_D_keel Is Nothing Then
        disp_D_keel.Dimension.Name = "D3"
        disp_D_keel.Dimension.SystemValue = 0.040000000  ' 40 mm
    Else
        Debug.Print "FAIL  D_keel (D3) - AddDimension2 returned Nothing; the selection above may not support a swDistanceDim"
    End If

    ' D_waterline (D4): vertical on P_origin, P_stbd
    Part.ClearSelection2 True
    v_P_origin.Select4 False, Nothing
    v_P_stbd.Select4 True, Nothing
    Dim disp_D_waterline As Object
    Set disp_D_waterline = Part.Extension.AddDimension2(0.018000000, 0.000000000, 0)
    If Not disp_D_waterline Is Nothing Then
        disp_D_waterline.Dimension.Name = "D4"
        disp_D_waterline.Dimension.SystemValue = 0.000000000  ' 0 mm
    Else
        Debug.Print "FAIL  D_waterline (D4) - AddDimension2 returned Nothing; the selection above may not support a swDistanceDim"
    End If

    ' SW-MANUAL: D_SU_start (D5, distance) cannot be a live COM call - see the file
    ' header. By hand:
    '   1. select the forward-reaching arrow of the handle on point 1 of SP_stbd_upper
    '   2. Smart Dimension, targeting swDistanceDim (distance)
    '   value: 0.003785559 m (3.7855590004629884 mm)

    ' SW-MANUAL: D_SU_end (D6, distance) cannot be a live COM call - see the file
    ' header. By hand:
    '   1. select the back-reaching arrow of the handle on point 9 of SP_stbd_upper
    '   2. Smart Dimension, targeting swDistanceDim (distance)
    '   value: 0.004728045 m (4.728045458392398 mm)

    ' SW-MANUAL: D_SL_start (D7, distance) cannot be a live COM call - see the file
    ' header. By hand:
    '   1. select the forward-reaching arrow of the handle on point 1 of SP_stbd_lower
    '   2. Smart Dimension, targeting swDistanceDim (distance)
    '   value: 0.003877667 m (3.8776669759158042 mm)

    ' SW-MANUAL: D_SL_end (D8, distance) cannot be a live COM call - see the file
    ' header. By hand:
    '   1. select the back-reaching arrow of the handle on point 7 of SP_stbd_lower
    '   2. Smart Dimension, targeting swDistanceDim (distance)
    '   value: 0.006308006 m (6.308006174731335 mm)

    ' SW-MANUAL: D_PU_start (D9, distance) cannot be a live COM call - see the file
    ' header. By hand:
    '   1. select the forward-reaching arrow of the handle on point 1 of SP_port_upper
    '   2. Smart Dimension, targeting swDistanceDim (distance)
    '   value: 0.003785559 m (3.7855590004629884 mm)

    ' SW-MANUAL: D_PU_end (D10, distance) cannot be a live COM call - see the file
    ' header. By hand:
    '   1. select the back-reaching arrow of the handle on point 9 of SP_port_upper
    '   2. Smart Dimension, targeting swDistanceDim (distance)
    '   value: 0.004728045 m (4.728045458392398 mm)

    ' SW-MANUAL: D_PL_start (D11, distance) cannot be a live COM call - see the file
    ' header. By hand:
    '   1. select the forward-reaching arrow of the handle on point 1 of SP_port_lower
    '   2. Smart Dimension, targeting swDistanceDim (distance)
    '   value: 0.003877667 m (3.8776669759158042 mm)

    ' SW-MANUAL: D_PL_end (D12, distance) cannot be a live COM call - see the file
    ' header. By hand:
    '   1. select the back-reaching arrow of the handle on point 7 of SP_port_lower
    '   2. Smart Dimension, targeting swDistanceDim (distance)
    '   value: 0.006308006 m (6.308006174731335 mm)



    ' Close the sketch and give it its final name.
    Dim swSketch As Object
    Set swSketch = Part.SketchManager.ActiveSketch
    Part.SketchManager.InsertSketch True
    If Not swSketch Is Nothing Then
        On Error Resume Next
        swSketch.GetFeature().Name = "S4_section"
        On Error GoTo 0
    End If
End Sub
