' SparPath3D.bas - generated by fus (Fuselage-Builder). Do not hand-edit; regenerate from fuselage.json.
'
' UNITS: every coordinate, radius and linear dimension below is in METRES, the
' SolidWorks API's own unit. This sketch's source data is millimetres; each value
' has already been divided by 1000 on the way out. Angle values (radians) are
' unconverted. See src/sketch3d/sw3d.ts if this macro's shape looks 1000x too big
' or too small - the same hazard src/sketch/sw.ts's 2D macro guards against.
'
' PLANE: a 3D sketch is not hosted on a plane or a face, so unlike the 2D macro
' this file never asks you to select one before running it - CreatePoint,
' CreateLine2 and CreateSpline below all take three real coordinates. Arc and
' Circle are the exception: whether CreateArc/CreateCircleByRadius honour their
' own three coordinates' plane inside a 3D sketch, or resolve against whatever
' plane happens to be active, is an open question nothing in this repo has a
' SolidWorks instance to settle (docs/SKETCH3D-PLAN.md §6 P7b) - UNVERIFIED. So
' every arc and circle below is drawn by hand instead of guessed, with its own
' points already placed live for you to snap to.
'
' ENTITIES: 6   RELATIONS: 2   DIMENSIONS: 1
' MANUAL STEPS: 2 - this sketch cannot be fully automated over COM. Marked
' "SW-MANUAL:" below, and counted here rather than left to be discovered:
'   - 1 arc/circle entity(ies) - plane behaviour unverified, see above
'   - 1 interior point(s) that also stand in for another point, not welded to their own curve
'
' This file's mapping from this app's relation/dimension vocabulary to SolidWorks'
' own names is RELATION_CONSTRAINT_3D / DIMENSION_TYPE_3D in src/sketch3d/sw3d.ts,
' not repeated per-line here. Verified as well-formed VBA against the documented
' API surface where one exists; not executed against SolidWorks, which nothing in
' this repo has.
'
Option Explicit

Sub CreateSketch()
    Dim swApp As Object, Part As Object
    Set swApp = Application.SldWorks
    Set Part = swApp.ActiveDoc
    If Part Is Nothing Then
        MsgBox "Open the target part first."
        Exit Sub
    End If

    ' A 3D sketch is not hosted on a plane or a face - see the header.
    Part.SketchManager.Insert3DSketch2 True

    ' ------------------------------------------------------------ entities
    ' P_root
    Dim v_P_root As Object
    Set v_P_root = Part.SketchManager.CreatePoint(0.000000000, 0.000000000, 0.040000000)

    ' P_mid
    Dim v_P_mid As Object
    Set v_P_mid = Part.SketchManager.CreatePoint(0.120000000, 0.055000000, 0.030000000)

    ' P_tip
    Dim v_P_tip As Object
    Set v_P_tip = Part.SketchManager.CreatePoint(0.260000000, 0.000000000, -0.010000000)

    ' L_spar: line P_root -> P_tip
    Dim v_L_spar As Object
    Set v_L_spar = Part.SketchManager.CreateLine2(0.000000000, 0.000000000, 0.040000000, 0.260000000, 0.000000000, -0.010000000)
    v_L_spar.ConstructionGeometry = True
    Part.ClearSelection2 True
    v_P_root.Select4 False, Nothing
    v_L_spar.GetStartPoint2().Select4 True, Nothing
    Part.SketchManager.AddConstraint "sgCOINCIDENT"  ' weld: L_spar start == P_root
    Part.ClearSelection2 True
    v_P_tip.Select4 False, Nothing
    v_L_spar.GetEndPoint2().Select4 True, Nothing
    Part.SketchManager.AddConstraint "sgCOINCIDENT"  ' weld: L_spar end == P_tip

    ' SP_edge: spline through P_root, P_mid, P_tip
    Dim pts_SP_edge(8) As Double
    pts_SP_edge(0) = 0.000000000 : pts_SP_edge(1) = 0.000000000 : pts_SP_edge(2) = 0.040000000
    pts_SP_edge(3) = 0.120000000 : pts_SP_edge(4) = 0.055000000 : pts_SP_edge(5) = 0.030000000
    pts_SP_edge(6) = 0.260000000 : pts_SP_edge(7) = 0.000000000 : pts_SP_edge(8) = -0.010000000
    Dim v_SP_edge As Object
    Set v_SP_edge = Part.SketchManager.CreateSpline(pts_SP_edge)
    Part.ClearSelection2 True
    v_P_root.Select4 False, Nothing
    v_SP_edge.GetStartPoint2().Select4 True, Nothing
    Part.SketchManager.AddConstraint "sgCOINCIDENT"  ' weld: SP_edge start == P_root
    Part.ClearSelection2 True
    v_P_tip.Select4 False, Nothing
    v_SP_edge.GetEndPoint2().Select4 True, Nothing
    Part.SketchManager.AddConstraint "sgCOINCIDENT"  ' weld: SP_edge end == P_tip
    ' SW-MANUAL: P_mid is both an interior point of SP_edge and a standalone point
    ' this file did create (it plays a boundary role elsewhere - see
    ' standalonePointIds3d). CreateSpline above still minted its own coincident point
    ' at the same location rather than reusing v_P_mid; there is no
    ' documented call here to select a spline's Nth interior point by index and weld
    ' it. By hand: select that interior point on SP_edge in the graphics area and add
    ' a Coincident relation to P_mid.

    ' C_ring: circle, centre P_mid, r=18mm, normal [1, 0, 0]
    ' SW-MANUAL: C_ring (circle) - CreateCircleByRadius's plane behaviour inside a 3D
    ' sketch is UNVERIFIED (docs/SKETCH3D-PLAN.md §6 P7b) - drawn by hand rather than
    ' guessed. By hand:
    '   1. select the already-created point for P_mid (its centre, 120.00, 55.00, 30.00 mm)
    '   2. Tools > Sketch Entities > Circle, radius 18.00 mm, normal [1.0000, 0.0000, 0.0000]
    '   3. Esc/Enter to finish

    ' ----------------------------------------------------------- relations
    ' R_along: coincident on P_root, SP_edge
    Part.ClearSelection2 True
    v_P_root.Select4 False, Nothing
    v_SP_edge.Select4 True, Nothing
    Part.SketchManager.AddConstraint "sgCOINCIDENT"

    ' R_fix_root: fix on P_root
    Part.ClearSelection2 True
    v_P_root.Select4 False, Nothing
    Part.SketchManager.AddConstraint "sgFIXED"


    ' ---------------------------------------------------------- dimensions
    ' D_span (D1): distance on P_root, P_tip
    Part.ClearSelection2 True
    v_P_root.Select4 False, Nothing
    v_P_tip.Select4 True, Nothing
    Dim disp_D_span As Object
    Set disp_D_span = Part.Extension.AddDimension2(0.000000000, 0.000000000, 0.000000000)
    If Not disp_D_span Is Nothing Then
        disp_D_span.Dimension.Name = "D1"
        disp_D_span.Dimension.SystemValue = 0.260000000  ' 260 mm
    Else
        Debug.Print "FAIL  D_span (D1) - AddDimension2 returned Nothing; the selection above may not support a swDistanceDim"
    End If



    ' Close the 3D sketch and give it its final name.
    Dim swSketch As Object
    Set swSketch = Part.SketchManager.ActiveSketch
    Part.SketchManager.Insert3DSketch2 True
    If Not swSketch Is Nothing Then
        On Error Resume Next
        swSketch.GetFeature().Name = "SparPath3D"
        On Error GoTo 0
    End If
End Sub
